FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:edge

RUN dpkg --add-architecture armhf

# RUN apt-get update && apt-get install -y build-essential \
#    libasound2-dev:armhf portaudio19-dev:armhf libpulse-dev:armhf \
#    libdbus-1-dev:armhf \
#    libespeak-ng-dev:armhf \
#    espeak-ng:armhf \
#    clang

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Warsaw \
    apt-get install --assume-yes --no-install-recommends libspeechd-dev:armhf libclang-dev clang

ENV PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig/:${PKG_CONFIG_PATH}"
# ENV PKG_CONFIG_ALLOW_CROSS="true"

COPY ./docker/toolchain.cmake /opt/toolchain.cmake

# ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS="-L /usr/lib/arm-linux-gnueabihf -C link-args=-Wl,-rpath-link,/usr/lib/arm-linux-gnueabihf $CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS"